# Generated by Django 3.2.5 on 2021-07-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookmodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.usermodel'),
        ),
    ]
